export default {
  publishers: [
    {'aid': 'ozdSXZ1QtZ', 'name': 'ChivasTV', 'mode': 4},
    {'aid': '4rqMYyzEyD', 'name': 'Ad Age', 'mode': 4},
    {'aid': 'g2boT3JL8Y', 'name': 'America tvGO', 'mode': 4},
    {'aid': '1dbn26FN2h', 'name': 'Asburypark-NJ', 'mode': 4},
    {'aid': 'Sd3ZilgKjO', 'name': 'Asheboro Courier-Tribune', 'mode': 5},
    {'aid': 'OVPX39SVkl', 'name': 'Asheville-NC', 'mode': 4},
    {'aid': 'l6rB2ooK2U', 'name': 'AwesomenessTV', 'mode': 2},
    {'aid': 'IHFDsFInrJ', 'name': 'Bloomberg', 'mode': 2},
    {'aid': 'jXqAWZPnMt', 'name': 'Brockton Enterprise', 'mode': 5},
    {'aid': 'xcosBLUEqh', 'name': 'Burlington Times-News', 'mode': 5},
    {'aid': 'B6sIXKLiin', 'name': 'Business Insider', 'mode': 5},
    {'aid': '6Cs63MZ7Vq', 'name': 'Calgary Herald', 'mode': 2},
    {'aid': 'oPXnV0nJUY', 'name': 'Canandaigua Daily Messenger', 'mode': 5},
    {'aid': 'GKN8hZ8XaZ', 'name': 'Canton Repository', 'mode': 5},
    {'aid': 'pZpDrRDtBy', 'name': 'Cleveland.com', 'mode': 2},
    {'aid': 'o19WonOrHQ', 'name': 'CNBC', 'mode': 2},
    {'aid': '3xTFZElLju', 'name': 'Coldwater Daily Reporter', 'mode': 5},
    {'aid': '6LBQaM0h3i', 'name': 'Coloradoan', 'mode': 4},
    {'aid': 'uxkfYvNaRE', 'name': 'Columbia Daily Tribune', 'mode': 5},
    {'aid': 'GnVyObE5Pf', 'name': 'Crikey', 'mode': 2},
    {'aid': '6mFfluDnUN', 'name': 'Daily Herald', 'mode': 2},
    {'aid': 'MjpK0Y75KD', 'name': 'Daily Telegram', 'mode': 5},
    {'aid': 'auRyMIR0sY', 'name': 'Daily-Chronicle.com', 'mode': 5},
    {'aid': 'DgVOcpgpKg', 'name': 'Daytona Beach News-Journal', 'mode': 5},
    {'aid': 'zkWRYPrt7G', 'name': 'Decider', 'mode': 2},
    {'aid': '24vLLRnBui', 'name': 'Diario de Pernambuco', 'mode': 2},
    {'aid': '6LaRkvUre6', 'name': 'Digiday', 'mode': 2},
    {'aid': 'OUhqozF150', 'name': 'Dumont KSTA', 'mode': 2},
    {'aid': 'NgrKzFTlSg', 'name': 'Edmonton Journal', 'mode': 2},
    {'aid': 'kVw77VOIDd', 'name': 'El Espectador', 'mode': 2},
    {'aid': '8vZARyTVSg', 'name': 'El Nuevo Dia PRODUCCION', 'mode': 2},
    {'aid': 'Vwz55KjN9n', 'name': 'El Paso', 'mode': 4},
    {'aid': 'Ut7aooJNHB', 'name': 'El Universal of Cartegena', 'mode': 1},
    {'aid': 'AmiI19JrR5', 'name': 'Fall River Herald News', 'mode': 5},
    {'aid': 'bYLvuWS6m1', 'name': 'Fayetteville Observer', 'mode': 5},
    {'aid': 'rz1uH1WkXu', 'name': 'Financial Post', 'mode': 2},
    {'aid': 'KUO5665218', 'name': 'Fortune', 'mode': 2},
    {'aid': 'qrPu7RttTE', 'name': 'FUNKE MEDIEN NRW', 'mode': 2},
    {'aid': 'kqzxaJ8VYt', 'name': 'Gadsden Times', 'mode': 5},
    {'aid': 'fd8VL3oOxI', 'name': 'Gainesville Sun', 'mode': 5},
    {'aid': 'nSfEaiFRCu', 'name': 'Galesburg Register-Mail', 'mode': 5},
    {'aid': '2YTwbbhc3E', 'name': 'Gaston Gazette', 'mode': 5},
    {'aid': 'bYdYZQml5V', 'name': 'GlobalSecurity.org', 'mode': 4},
    {'aid': 'LiB66Tw2pe', 'name': 'Globe and Mail – ARC', 'mode': 4},
    {'aid': 'zUkajvWJ04', 'name': 'Golf Digest', 'mode': 2},
    {'aid': 'WrIuhgmmrp', 'name': 'Goop', 'mode': 2},
    {'aid': 'TU3JZ1dtYf', 'name': 'Greenville-SC', 'mode': 4},
    {'aid': '3vxSO5Sezi', 'name': 'Grupo Abril', 'mode': 2},
    {'aid': 'KH6Y7Oav4R', 'name': 'Hendersonville Times-News', 'mode': 5},
    {'aid': 'rBSKi8pTte', 'name': 'Herald Scotland', 'mode': 2},
    {'aid': 'JEixpRaLbs', 'name': 'Holland Sentinel', 'mode': 5},
    {'aid': 'DxonTvzGrx', 'name': 'Houma Today', 'mode': 5},
    {'aid': '5JH3r2kxpL', 'name': 'IDC Online', 'mode': 2},
    {'aid': 'GTCopIDc5z', 'name': 'Infoglobo, Editora e Condé Nast', 'mode': 2},
    {'aid': 'NjBp7rufIn', 'name': 'Investors Business Daily', 'mode': 2},
    {'aid': 'UdxU536vyi', 'name': 'Jacksonville Daily News', 'mode': 5},
    {'aid': 'zteDqZhc6i', 'name': 'Journal-Standard', 'mode': 5},
    {'aid': 'E1P0AqK62n', 'name': 'Kent Record-Courier', 'mode': 5},
    {'aid': 'wIi3W16Pfq', 'name': 'La Opinion', 'mode': 2},
    {'aid': '2i7PM9IsoZ', 'name': 'La Patria of Manizales', 'mode': 1},
    {'aid': 'hosLu9lGKn', 'name': 'La Voz', 'mode': 2},
    {'aid': 'DKhb3j5Ysv', 'name': 'Lafayette-LA', 'mode': 4},
    {'aid': 'SDDk6QgkeK', 'name': 'Las Vegas Sun', 'mode': 2},
    {'aid': 'bLFC1c5lTd', 'name': 'Lexington Dispatch', 'mode': 5},
    {'aid': 'NsZ8w1B42e', 'name': 'London Review Of Books', 'mode': 2},
    {'aid': '6JGu3l9sVZ', 'name': 'Louisville-KY', 'mode': 4},
    {'aid': 'zmAnt5zvpQ', 'name': 'MetroWest Daily News', 'mode': 5},
    {'aid': '38mM7L549G', 'name': 'Monroe News', 'mode': 5},
    {'aid': 'hdL5mHxkQj', 'name': 'Montreal Gazette', 'mode': 2},
    {'aid': 'ZiZxr0ulLn', 'name': 'Mundo Estranho', 'mode': 2},
    {'aid': 'Z9bvuPACYA', 'name': 'National Observer', 'mode': 5},
    {'aid': 'SE0WzqlbUG', 'name': 'National Post', 'mode': 2},
    {'aid': 'ZNdalw3GlS', 'name': 'National Review', 'mode': 2},
    {'aid': 'Je5wPuCjpI', 'name': 'NBC Sports Gold', 'mode': 2},
    {'aid': 'CiHbOCZ1pg', 'name': 'Nemzeti Sport', 'mode': 4},
    {'aid': 'PEmPwiV5hR', 'name': 'New Bern Sun Journal', 'mode': 5},
    {'aid': 'MH9NDnRj2b', 'name': 'New York Post', 'mode': 2},
    {'aid': '7wt2qUDI6D', 'name': 'NewtonDailyNews.com', 'mode': 5},
    {'aid': 'mq4ucQHSOB', 'name': 'NJ.com', 'mode': 2},
    {'aid': 'euFbM9LHvo', 'name': 'Northwest Florida Daily News', 'mode': 5},
    {'aid': 'oE2keIoTBa', 'name': 'Norwich Bulletin', 'mode': 5},
    {'aid': 'HP2wbBsiUk', 'name': 'NWHerald.com', 'mode': 5},
    {'aid': 'sUi7a62VEA', 'name': 'NYMag', 'mode': 2},
    {'aid': 'FbygckNZIG', 'name': 'Ocala Star Banner', 'mode': 5},
    {'aid': 'fTIAeCZOih', 'name': 'Olé', 'mode': 2},
    {'aid': '8FKonEClNM', 'name': 'Otago Daily Times', 'mode': 2},
    {'aid': 'aMpZA5bBzp', 'name': 'Ottawa Citizen', 'mode': 2},
    {'aid': '6NqheC4DIa', 'name': 'Page Six', 'mode': 2},
    {'aid': 'PPuKBEJM2H', 'name': 'Panama City News Herald', 'mode': 5},
    {'aid': 'qdm4j5vcaE', 'name': 'Patriot Ledger', 'mode': 5},
    {'aid': 'FX5ZKBJbdJ', 'name': 'Peoria Journal Star', 'mode': 5},
    {'aid': 'uRjKJzXgZJ', 'name': 'Pocono Record', 'mode': 5},
    {'aid': 'XbtscClvMf', 'name': 'Post and Courier', 'mode': 2},
    {'aid': 'pV38esXWbF', 'name': 'Público (PT)', 'mode': 2},
    {'aid': 'GFdB9BIGF4', 'name': 'RASP PL', 'mode': 4},
    {'aid': 'rJ8lIP2AXv', 'name': 'Regina Leader-Post', 'mode': 2},
    {'aid': 'QqCih7hc7z', 'name': 'Rochester-NY', 'mode': 4},
    {'aid': 'onTD1CEf90', 'name': 'Rockford Register Star', 'mode': 5},
    {'aid': 'O4e8pFYZAQ', 'name': 'Rolla Daily News', 'mode': 5},
    {'aid': 'RV43F7VQwt', 'name': 'Sarasota Herald-Tribune', 'mode': 5},
    {'aid': 'V9bYavcKo3', 'name': 'Saskatoon StarPhoenix', 'mode': 2},
    {'aid': 'dRdGTybhWh', 'name': 'Science Magazine', 'mode': 2},
    {'aid': 'lm3S6tjB3v', 'name': 'Shelby Star', 'mode': 5},
    {'aid': '4NRXN0s9bS', 'name': 'SME.sk', 'mode': 2},
    {'aid': '4OGmtvd8fA', 'name': 'Southwest Times Record', 'mode': 5},
    {'aid': 'MWmKlwwKAu', 'name': 'Spartanburg Herald-Journal', 'mode': 5},
    {'aid': 'JPtBu2rJXw', 'name': 'StarNews Media', 'mode': 5},
    {'aid': 'Y6eDVlUTyK', 'name': 'Stars and Stripes', 'mode': 5},
    {'aid': 'AJqYpQXxpe', 'name': 'State Journal-Register', 'mode': 5},
    {'aid': 'IiWNtF2lON', 'name': 'Stitcher', 'mode': 2},
    {'aid': 'RjIJhdc4Gz', 'name': 'Stratfor', 'mode': 2},
    {'aid': '0vOoag8WO8', 'name': 'Taunton Daily Gazette', 'mode': 5},
    {'aid': 'Fy7FpgyUxA', 'name': 'TechCrunch', 'mode': 2},
    {'aid': '9V33tWRvZX', 'name': 'Telegram & Gazette', 'mode': 5},
    {'aid': 'T3YM3Xptd7', 'name': 'Tennessean', 'mode': 4},
    {'aid': 'xvOdxWLORG', 'name': 'The Ames Tribune', 'mode': 5},
    {'aid': 'Wjb1thKaGB', 'name': 'The Columbus Dispatch', 'mode': 5},
    {'aid': '2SUjiFgnKP', 'name': 'The Daily Caller', 'mode': 4},
    {'aid': 'zal9xGNryV', 'name': 'The Daily Mash', 'mode': 4},
    {'aid': 'Nmww1v3ps0', 'name': 'The Dallas Morning News', 'mode': 2},
    {'aid': 'CgenXrprgH', 'name': 'The Economist', 'mode': 2},
    {'aid': 'd4XLDKwgVK', 'name': 'The Gazette', 'mode': 2},
    {'aid': 'bF2qPWAkzX', 'name': 'The Hamilton Spectator', 'mode': 5},
    {'aid': 'PEnWb6dCNR', 'name': 'The Ledger', 'mode': 5},
    {'aid': 'lGr3ciYmC7', 'name': 'The Local', 'mode': 2},
    {'aid': 'NL1bHJZ2Gr', 'name': 'The National', 'mode': 2},
    {'aid': '4OyhLrCXej', 'name': 'The Northern Echo', 'mode': 2},
    {'aid': 'ZEx4xsXir7', 'name': 'The Players Tribune', 'mode': 2},
    {'aid': 'YWW5kTdi4s', 'name': 'The Progress-Index', 'mode': 5},
    {'aid': '8H6C7Vf5wd', 'name': 'The Providence Journal', 'mode': 5},
    {'aid': 'XFtUpaGGsj', 'name': 'The Province', 'mode': 2},
    {'aid': 'p7sVIGTDn5', 'name': 'The Real Deal', 'mode': 2},
    {'aid': '2quqqDpmEk', 'name': 'The Star Press', 'mode': 4},
    {'aid': 'kezhOUsdkF', 'name': 'theCHIVE', 'mode': 2},
    {'aid': 'PgTr0GAP50', 'name': 'TheHerald-News.com', 'mode': 5},
    {'aid': 'QSha5LMb1W', 'name': 'Thibodaux Daily Comet', 'mode': 5},
    {'aid': 'L9op1iXFtk', 'name': 'Times Colonist', 'mode': 5},
    {'aid': '6dQcrgMVS0', 'name': 'Times Publishing Co.', 'mode': 2},
    {'aid': 'HiriJLjakh', 'name': 'Tuscaloosa News', 'mode': 5},
    {'aid': 'ZRDrnyBkBx', 'name': 'USA Today', 'mode': 4},
    {'aid': 'fqLlKt4pz7', 'name': 'Utica Observer-Dispatch', 'mode': 5},
    {'aid': 'E9moANse1G', 'name': 'Vancouver Sun', 'mode': 2},
    {'aid': '19fnorq5ZP', 'name': 'Virginian-Pilot', 'mode': 2},
    {'aid': 'hION4ongk2', 'name': 'Voy De Viaje', 'mode': 2},
    {'aid': 'cxny6AIHSr', 'name': 'Westchester-NY', 'mode': 4},
    {'aid': 'Da1UqzLDLR', 'name': 'Wicked Local', 'mode': 5},
    {'aid': 'kvh83nNiMM', 'name': 'Windsor Star', 'mode': 2},
    {'aid': 'cqVXn4kcJp', 'name': 'Wooster Daily Record', 'mode': 5},
    {'aid': 'aodSqJHN7V', 'name': 'York', 'mode': 4}
  ]
}
